--[[
Settings config
]]--

SCREENWIDTH = 800
SCREENHEIGHT = 600
TIMER = 60
SKYBOX_SIZE = 1000
ENEMY_TOP_LEFT = 7
ENEMY_TOP_RIGHT = 7
ENEMY_BOTTOM_LEFT = 7
ENEMY_BOTTOM_RIGHT = 7
TREE_MIN_VALUE = -230
TREE_MAX_VALUE = 470
TREE_DISTANCE_BETWEEN = 70